const FrutasImages = {
   macaGrey: require('../assets/frutas/macaGrey.png'),
   abacate:require('../assets/frutas/abacateRed.png'),
   abacaxi: require('../assets/frutas/abacaxiRed.png'),
   acai: require('../assets/frutas/acaiRed.png'),
   acerola: require('../assets/frutas/acerolaRed.png'),
   ameixa: require('../assets/frutas/ameixaRed.png'),
   amora: require('../assets/frutas/amoraRed.png'),
   ariticum: require('../assets/frutas/araticumRed.png'),
   atemoia: require('../assets/frutas/atemoiaRed.png'),
   banana: require('../assets/frutas/bananaRed.png'),
   bergamota: require('../assets/frutas/bergamotaRed.png'),
   cacau: require('../assets/frutas/cacauRed.png'),
   caju: require('../assets/frutas/cajuRed.png'),
   caqui: require('../assets/frutas/caquiRed.png'),
   carambola: require('../assets/frutas/carambolaRed.png'),
   cereja: require('../assets/frutas/cerejaRed.png'),
   coco: require('../assets/frutas/cocoRed.png'),
   dekopon: require('../assets/frutas/dekoponRed.png'),
   figo: require('../assets/frutas/figoRed.png'),
   framboesa: require('../assets/frutas/framboesaRed.png'),
   frutadoconde: require('../assets/frutas/frutadocondeRed.png'),
   frutapao: require('../assets/frutas/frutapaoRed.png'),
   guarana: require('../assets/frutas/guaranaRed.png'),
   jabuticaba: require('../assets/frutas/jabuticabaRed.png'),
   jaca: require('../assets/frutas/jacaRed.png'),
   kiwi: require('../assets/frutas/kiwiRed.png'),
   laranja: require('../assets/frutas/laranjaRed.png'),
   lichia: require('../assets/frutas/lichiaRed.png'),
   limao: require('../assets/frutas/limaoRed.png'),
   lima: require('../assets/frutas/limaRed.png'),
   maca: require('../assets/frutas/macaRed.png'),
   mamao: require('../assets/frutas/mamaoRed.png'),
   manga: require('../assets/frutas/mangaRed.png'),
   maracuja: require('../assets/frutas/maracujaRed.png'),
   melancia: require('../assets/frutas/melanciaRed.png'),
   melao: require('../assets/frutas/melaoRed.png'),
   mexerica: require('../assets/frutas/mexericaRed.png'),
   morango: require('../assets/frutas/morangoRed.png'),
   nectarina: require('../assets/frutas/nectarinaRed.png'),
   nespera: require('../assets/frutas/nesperaRed.png'),
   pera: require('../assets/frutas/peraRed.png'),
   pessego: require('../assets/frutas/pessegoRed.png'),
   physalis: require('../assets/frutas/physalisRed.png'),
   pitaia: require('../assets/frutas/pitaiaRed.png'),
   pitanga: require('../assets/frutas/pitangaRed.png'),
   roma: require('../assets/frutas/romaRed.png'),
   tangerina: require('../assets/frutas/tangerinaRed.png'),
   uva: require('../assets/frutas/uvaRed.png'),
   vergamota: require('../assets/frutas/vergamotaRed.png'),
};

export default FrutasImages;